global-quest-display:
  lore:
#    append-normal:
#      - "..."
    append-not-started:
      - ""
      - "&eLeft Click &7to start this quest."
    append-started:
      - ""
      - "&aYou have started this quest."
      - "&eMiddle Click &7to track this quest."
      - "&eRight Click &7to cancel this quest."
    append-tracked:
      - ""
      - "&aYou are &etracking &athis quest."
      - "&eMiddle Click &7to stop tracking this quest."
      - "&eRight Click &7to cancel this quest."

# Macros for faster quests configuration without having to repeat
# yourself.
# See wiki for more information.
global-macros:
  bar: "&6---&7---&6---"

# Configure titles
titles:
  quest-start:
    title: "&cQuest Started"
    subtitle: "&7{quest}"
  quest-complete:
    title: "&cQuest Complete"
    subtitle: "&7{quest}"

# Configure messages
messages:
  time-format: "{hours}h {minutes}m"
  quest-start: "&7Quest &c{quest} &7started!"
  quest-complete: "&7Quest &c{quest} &7completed!"
  quest-cancel: "&7Quest &c{quest} &7cancelled!"
  quest-expire: "&7Quest &c{quest} &7has expired."
  quest-track: "&7Tracking quest &c{quest}&7."
  quest-track-stop: "&7No longer tracking quest &c{quest}&7."
  quest-random-none: "&cYou have no quests which you can start."
  quest-start-limit: "&7Players are limited to &c{limit} &7started quests at a time."
  quest-start-disabled: "&7You cannot repeat this quest."
  quest-start-locked: "&7You have not unlocked this quest yet."
  quest-start-cooldown: "&7You have recently completed this quest. You have to wait &c{time} &7until you are able to restart it."
  quest-start-started: "&7You have already started this quest."
  quest-start-permission: "&7You do not have permission to start this quest."
  quest-category-permission: "&7You do not have permission to view this category."
  quest-category-quest-permission: "&7You do not have permission to start this quest since it is in a category you do not have permission to view."
  quest-cancel-notstarted: "&7You have not started this quest."
  quest-cancel-notcancellable: "&7You cannot cancel this quest."
  quest-updater: "&cQuests > &7A new version &c{newver} &7was found on Spigot (your version: &c{oldver}&7). Please update me! <3 - Link: {link}"
  command-data-not-loaded: "&4Your quests progress file has not been loaded; you cannot use quests. If this issue persists, contact an admin."
  command-sub-doesntexist: "&7The specified subcommand '&c{sub}' &7does not exist."
  command-quest-cancel-specify: "&7You must specify a quest to cancel."
  command-quest-start-doesntexist: "&7The specified quest '&c{quest}&7' does not exist."
  command-quest-general-doesntexist: "&7The specified quest '&c{quest}&7' does not exist."
  command-category-open-disabled: "&7Categories are disabled."
  command-category-open-doesntexist: "&7The specified category '&c{category}&7' does not exist."
  command-quest-admin-playernotfound: "&7Player '&c{player}&7' could not be found."
  command-quest-openquests-admin-success: "&7Opened Quest GUI for player &c{player}&7."
  command-quest-openstarted-admin-success: "&7Opened started Quest GUI for player &c{player}&7."
  command-quest-opencategory-admin-success: "&7Opened category &c{category} &7for player &c{player}&7."
  command-taskview-admin-fail: "&7Task type '&c{task}&7' does not exist."
  beta-reminder: "&cQuests > &7Reminder: you are currently using a &cbeta &7version of Quests. Please send bug reports to https://github.com/LMBishop/Quests/issues and check for updates regularly using &c/quests admin update&7!"
  command-quest-admin-loaddata: "&7Quest data for '&c{player}&7' is being loaded."
  command-quest-admin-nodata: "&7No data could be found for player &c{player}&7."
  command-quest-admin-fullreset: "&7Data for player &c{player}&7 has been fully reset."
  command-quest-admin-start-faillocked: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have not yet unlocked it."
  command-quest-admin-start-failcooldown: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is still on cooldown for them."
  command-quest-admin-start-failcomplete: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have already completed it."
  command-quest-admin-start-faillimit: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have reached their quest start limit."
  command-quest-admin-start-failstarted: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is already started."
  command-quest-admin-start-failpermission: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission."
  command-quest-admin-start-failcategorypermission: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission for the category which the quest is in."
  command-quest-admin-start-failother: "&7Quest '&c{quest}&7' could not be started for player &c{player}&7."
  command-quest-admin-start-success: "&7Quest &c{quest} &7started for player &c{player}&7."
  command-quest-admin-category-permission: "&7Category &c{category} &7 could not be opened for player &c{player}&7. They do not have permission to view it."
  command-quest-admin-complete-success: "&7Quest &c{quest} &7completed for player &c{player}&7."
  command-quest-admin-reset-success: "&7Successfully reset quest '&c{quest}&7' for player &c{player}&7."
  command-quest-admin-random-none: "&7Player &c{player}&7 has no quests which they can start."
  command-quest-admin-random-success: "&7Successfully started random quest '&c{quest}&7' for player &c{player}&7."
  command-quest-admin-random-category-none: "&7Player &c{player}&7 has no quests in category '&c{category}&7' which they can start."
  command-quest-admin-random-category-success: "&7Successfully started random quest '&c{quest}&7' from category '&c{category}&7' for player &c{player}&7."
  ui-placeholder-completed-true: "true"
  ui-placeholder-completed-false: "false"
  ui-placeholder-truncated: " +{amount} more"
  placeholderapi-true: "true"
  placeholderapi-false: "false"
  placeholderapi-no-tracked-quest: "No tracked quest"
  placeholderapi-data-not-loaded: "Data not loaded"