TQ1:
  Active: true
  ShortDescription: Tutorial Quest 1
  IntroText: "For starters. Remove those nasty sand blocks in the entrance will ya?"
  CompletedText: "Quest completed! Good job!"
  ## Rewards
  Rewards:
  ## Each reward needs to start with 'n' index"
  ## Type is the type of reward.
    '0':
      Type: SItem
      Item: Diamond_Sword
      Amount: 1
    ## Requirements
  Requirements:
    '0':
      Type: DoneQuest
      QuestID: None
      LVL: 10
  StoryLine:
    #special characters:
    # '<=)> -> <emote>
    Gorshok_1: "<=)> Let's get some food in us, and then we'll Whoa!"
    Player_1: "Where did you come from?"
    Gorshok_2: "<=O> Well, as you can see, I am merely sitting here and reviewing what we have deduced thus far. "
    Player_2: "You were gone for ages, and now you're suddenly sitting here musing to yourself? Where have you been, anyway?"
    Gorshok_3: "<=D> ..."
    Player_3:
      - "???"
      - "Hmmm"
      - "Will you say something?"
      - "Gorshok ?! Hellooooo !"
TQ2:
  Active: true
  ShortDescription: Tutorial Quest 2
  IntroText: "For starters. Remove those nasty sand blocks in the entrance will ya?"
  CompletedText: "Good job!"
  ## Rewards
  Rewards:
    ## Each reward needs to start with 'n' index"
    ## Type is the type of reward.
    '0':
      Type: SItem
      Item: Diamond_Sword
      Amount: 1
    ## Requirements
  Requirements:
    '0':
      Type: DoneQuest
      QuestID: TQ1
      LVL: 10
  StoryLine:
    Gorshok_1: "OFEMNFEOMNFOWEOFNWOENFR"

